### ISSUE TITLE
deeplab example

### ISSUE THREAD

**Issue by ilous12** [freedomtan/glDelegateBench#1]
Hey. nice work.

Did you have been test deeplab bytebuffer to bitmap?

I tried but. failed.

**Comment by freedomtan** [comment]
Don't understand what you mean by "deeplab bytebuffer to bitmap", the output tensor of ResizeBilinear_3 is not bitmap. You should run ArgMax to find the the label/category, then run something like `label_to_color_image()` in the [deeplab_demo.ipynb](https://github.com/tensorflow/models/blob/master/research/deeplab/deeplab_demo.ipynb)

**Comment by candrwow** [comment]
> Don't understand what you mean by "deeplab bytebuffer to bitmap", the output tensor of ResizeBilinear_3 is not bitmap. You should run ArgMax to find the the label/category, then run something like `label_to_color_image()` in the [deeplab_demo.ipynb](https://github.com/tensorflow/models/blob/master/research/deeplab/deeplab_demo.ipynb)

hello，is the result is in [0,1)?I convert outputs(bytebuffer) to float,found some value not in this range,I don't know if my code is right,I read google's example,some model contains MEAN/STD,this model's MEAN/STD is?
你好，之前学习过一些softmax的知识，区间在[0,1)，本项目的运行结果也是这个范围吗，我在运行后出现了负数与大于1的数，我不知道我的代码是否正确使用，谷歌案例里有几个模型对input数据进行了标准化处理，平均值和标准差在这个项目是否需要处理呢？
pic is 257*257.
测试图片刚好是257*257，代码里的关于pixel的一些使用可能不正确，但是应该不影响结果，这是我从我之前用tensorflow mobile分割deeplabv3的项目复制过来的代码修改后的。

 ```
        int[] pixels = new int[w * h];
        ByteBuffer imgData = ByteBuffer.allocate(1 * 257 * 257 * 3 * 4);
        ByteBuffer outputs = ByteBuffer.allocate(257 * 257 * 21 * 4);
        bitmap.getPixels(pixels, 0, w, 0, 0, w, h);
        for (int i = 0; i < pixels.length; ++i) {
            int pixelValue = pixels[i];
            imgData.putFloat((pixelValue >> 16) & 0xFF);
            imgData.putFloat((pixelValue >> 8) & 0xFF);
            imgData.putFloat(pixelValue & 0xFF);
        }

        long l = System.currentTimeMillis();
        interpreter.run(imgData, outputs);
        long l1 = System.currentTimeMillis();
        Log.d("MainActivity", "l1-1:" + (l1 - l));
        FloatBuffer fb = ((ByteBuffer) outputs.rewind()).asFloatBuffer();
        while (fb.hasRemaining())
            System.out.println(fb.position() + " -> " + fb.get());
```

**Comment by freedomtan** [comment]
@candrwow Mean and std are irrelevant. Input values are not normalized. To know the details, read DeepLab's code, esp. the [input preprocessing part](https://github.com/tensorflow/models/blob/master/research/deeplab/input_preprocess.py).

**Comment by freedomtan** [comment]
@candrwow oops, I checked DeepLab's code carefully just now, try mean=std=127.5 and do something like,
```
imgData.putFloat((((pixelValue >> 16) & 0xFF) - mean) / std );
....
```

**Comment by ilous12** [comment]
Hi. @freedomtan You are very kind. Thanks.

I saw your example.
> https://github.com/freedomtan/tensorflow/blob/deeplab_tflite_python/tensorflow/contrib/lite/examples/python/deeplab_segmentation.py

Is it support to run with "deeplabv3_257_mv_gpu.tflite"?
When I run, I saw below issue.

> Traceback (most recent call last):
>   File "deeplab_segmentation.py", line 143, in <module>
>     results = label_to_color_image(results).astype(np.uint8)
>   File "deeplab_segmentation.py", line 61, in label_to_color_image
>     raise ValueError('Expect 2-D input label')
> ValueError: Expect 2-D input label

**Comment by freedomtan** [comment]
@ilous12 nope, that one is for model cut after ArgMax, for `deeplabv3_257_mv_gpu.tflite`, which was cut before ArgMax, you have to add argmax, something like:
```
results = np.squeeze(np.argmax(output_data,3))
```
instead of
```
results = np.squeeze(output_data)
```

**Comment by ilous12** [comment]
Thanks you. It work.

**Comment by ilous12** [comment]
@freedomtan Very thanks your help.

please let me know if you know to print the contents of all tensors to standard output that is called in order?
