### ISSUE TITLE
Tested this App with Samsung Galaxy S9

### ISSUE THREAD

**Issue by Burgomehl** [freedomtan/glDelegateBench#2]
Thank you very much for this work. I just testet the app with my S9 and would like to share my results with you:

|model name|CPU 1 thread (ms)|CPU 4 threads (ms) |GPU (ms)|
|----------|------------:|-------------:|---:|
|Mobilenet | 43 | 72 | 41 |
|PoseNet   | 47 | 91 | 45 |
|DeepLab V3| 64 | 84 | 155 |
|Mobilenet SSD V2 COCO| 72| 164 | 73|

**Comment by freedomtan** [comment]
Interesting. Thanks for sharing. How come  CPU 4 threads numbers are much slower than CPU 1 thread? Scheduling problem? And GPU numbers do not look good?

**Comment by Burgomehl** [comment]
Yeah I think its something with scheduling problems. For the CPU 4 Threads. Tryed it again for 4 Threads and got different values each time. But they are not much better.

I came for the GPU test, because i hoped for better results. When i retrain the Mobilenet SSD V2 COCO and use it with my app which use the camera for input images i receive average times of 150ms per image with GPU and 300ms with CPU.

I have also tryed the GPU Demo from Tensorflow there i have an average of 45ms at GPU with Mobilenet

**Comment by freedomtan** [comment]
That's weird. What Galaxy S9 you use? As far as I know, there are at least two versions. One with Snapdragon 845; another with Exynos 8910. The Snapdragon 845's GPU is supposed to significantly better than Pixel 2's (which uses Snapdragon 835). I am not familiar with Samsung's phones. Is there something named performance mode or turbo mode that you can use to increase CPU and GPU clock frequencies? Or, if you can get root, try setting all clock frequencies, including CPU, GPU, memory, and other bus freqs, to maximum before running benchmarks. If none of above works, maybe open an issue to Tensorflow repo.

**Comment by Burgomehl** [comment]
I use the  Exynos 8910. 
Didn't found a turbo mode.
