### ISSUE TITLE
Different results on GPU and CPU

### ISSUE THREAD

**Issue by FedyuninV** [freedomtan/glDelegateBench#3]
Device: Sony XPeria XZ2 (SnapDragon 845)

I added 2 little modification to your app:

1) filling input buffers with fixed data
```java
private Object[] allocateInputBuffers(int[] shapes){
            int i_size = shapes.length;
            Object inputs[] = new Object[i_size];
            for (int i=0; i < i_size; i++) {
                ByteBuffer i_bytes = ByteBuffer.allocate(shapes[i]);
                float[] floats = new float[shapes[i] / 4];
                for(int j=0; j<floats.length; ++j) {
                    // Filling uniformly -5. ... 5.
                    floats[j] = ((float)j * 10) / floats.length - 5;
                }
                FloatBuffer fb = i_bytes.asFloatBuffer();
                fb.put(floats);
                i_bytes.rewind();
                Log.i("here: ", Float.toString(i_bytes.getFloat()) + " " + Float.toString(i_bytes.getFloat(4)));
                i_bytes.rewind();
                inputs[i] = i_bytes;
            }
            return inputs;
        }
```

2) printing first element of each output buffer
```java
String debugMessage = "";

            for (int i=0; i < loops; i++) {
                Object inputs[] = allocateInputBuffers(mModel.getInputShapes());
                Map<Integer, Object> outputs = allocateOutputBuffers(mModel.getOutputShapes());

                startTime = System.currentTimeMillis();
                interpreter.runForMultipleInputsOutputs(inputs, outputs);
                stopTime = System.currentTimeMillis();
                accTime += (stopTime - startTime);

                if(i == loops - 1) {
                    // on last step adding first element of output buffer to debugMessage
                    for (Map.Entry<Integer, Object> entry : outputs.entrySet()) {
                        ByteBuffer bb = (ByteBuffer) entry.getValue();
                        Log.i("here: ", "byteBufferLimit is : " + ((ByteBuffer) entry.getValue()).limit());
                        debugMessage += "    " + Float.toString(bb.getFloat(0)) + "\n";
                    }
                }
            }
            Log.i("here: ", "time: " + accTime/loops);
            resultMessage.setText("avg time: " + accTime/loops + " ms\n"
                + debugMessage);
```

And I get different outputs for every net (for ex. MobileNet v1).

CPU 1 thread output:
```
avg time: 97 ms
    -2.0144956
```

GPU output:
```
avg time: 21 ms
    0.0
```

What am I doing wrong?  Or is there any bugs in tensorflow-gpu

**Comment by freedomtan** [comment]
I am not sure if anything is wrong. Handling floating point number is tricky. Usually, modern CPUs have IEEE-754 conformant implementation. But GPUs may not. And most of time, people tend to use fp16 on GPUs to get better performance because for graphics and NN, accuracy of floating point number may not be so important. On CPUs, usually it's fp32.

**Comment by FedyuninV** [comment]
@freedomtan It does look like one of these scenarios:
1) I'm doing smth wrong
2) there is a bug in tflite

Because loss of accuracy, mentioned above, should lead to result somewhere at [-2.2; -1.8]. But exact zero value looks like one of these cases:

1) I'm taking data from net in wrong way or from wrong place
2) net didn't put result in the right place (or didn't calculate it at all)

**Comment by FedyuninV** [comment]
@freedomtan can you, please, reproduce this result on any of your devices?

**Comment by freedomtan** [comment]
I seldom write Java code. Since the source code of GPU Delegate is available, I hacked label_image and benchmark_model so that I can use C++ and command line to test if the delegate works as expected. So far so good. See my [hacks](https://github.com/tensorflow/tensorflow/compare/master...freedomtan:label_image_gl_delegate?expand=1)

**Comment by freedomtan** [comment]
Google guys made it possible to use the GPU Delegate in benchmark_model. My label_image patch is merged into the main TensorFlow repo. You may want to try them if you haven't.
