### ISSUE TITLE
Performance report for Nexus 5X 

### ISSUE THREAD

**Issue by ValYouW** [freedomtan/glDelegateBench#4]
Thanks for the app, not sure if anyone cares about Nexus 5X anymore, but these are the results I get:

|model name|CPU 1 thread (ms)|CPU 4 threads (ms) |GPU (ms)|
|----------|------------:|-------------:|---:|
|Mobilenet | 316 | 88 | 74 |
|PoseNet   | 376 | 105 | 142 |
|DeepLab V3| 479 | 169 | 304 |
|Mobilenet SSD V2 COCO| 533 | 180 | 150 |

Quite disappointing... I am specifically interested in object-detecion (ssd v2), and when testing the [Googles MediaPipe Object Detection Test App](https://github.com/google/mediapipe/tree/dc9216dc595585d495250d0692afe35985d816ff/mediapipe/examples/android/src/java/com/google/mediapipe/apps/objectdetectiongpu) it seems to be working quite fast (dont have measurements, only "feeling" when seeing the bounding boxes update). Did you played with MediaPipe? they did mention their OD model is trained with depth multiplier of 0.5, so I guess it's part of it...

**Comment by freedomtan** [comment]
Thanks for the numbers. As far as I know, MediaPipe doesn't use OpenCL backend of the GPU delegate yet. You may want to try it. Generally, I think OpenCL backend performs better than GL ES compute shade backend.
